#Used to Test Flair in List format
MLSFlairList = [
    { "flairLabel": "Major League Soccer", "flairClass": "MLS-MLS" },
    { "flairLabel": "Major League Soccer", "flairClass": "MLS-MLS2" },
    { "flairLabel": "Atlanta United FC", "flairClass": "MLS-ATL" },
    { "flairLabel": "Chicago Fire", "flairClass": "MLS-CHI" },
    { "flairLabel": "Colorado Rapids", "flairClass": "MLS-COL" },
    { "flairLabel": "Columbus Crew", "flairClass": "MLS-CLB" },
    { "flairLabel": "DC United", "flairClass": "MLS-DCU" },
    { "flairLabel": "FC Dallas", "flairClass": "MLS-DAL" },
    { "flairLabel": "Houston Dynamo", "flairClass": "MLS-HOU" },
    { "flairLabel": "LA Galaxy", "flairClass": "MLS-LAG" },
    { "flairLabel": "Los Angeles FC", "flairClass": "MLS-LAFC" },
    { "flairLabel": "Montreal Impact", "flairClass": "MLS-MTL" },
    { "flairLabel": "New England Revolution", "flairClass": "MLS-NER" },
    { "flairLabel": "New York Red Bulls", "flairClass": "MLS-NYRB" },
    { "flairLabel": "New York City FC", "flairClass": "MLS-NYCFC" },
    { "flairLabel": "Orlando City", "flairClass": "MLS-OCSC" },
    { "flairLabel": "Philadelphia Union", "flairClass": "MLS-PHI" },
    { "flairLabel": "Portland Timbers", "flairClass": "MLS-POR" },
    { "flairLabel": "Real Salt Lake", "flairClass": "MLS-RSL" },
    { "flairLabel": "Seattle Sounders", "flairClass": "MLS-SEA" },
    { "flairLabel": "Sporting Kansas City", "flairClass": "MLS-SKC" },
    { "flairLabel": "Toronto FC", "flairClass": "MLS-TOR" },
    { "flairLabel": "Vancouver Whitecaps", "flairClass": "MLS-VWC" }
]
NASLFlairList = [
    { "flairLabel": "North American Soccer League", "flairClass": "NASL-NASL" },
    { "flairLabel": "USL Pro", "flairClass": "USL-USL2" },
   
    { "flairLabel": "Carolina Railhawks", "flairClass": "NASL-CAR" },
    { "flairLabel": "FC Edmonton", "flairClass": "NASL-FCE" },
    { "flairLabel": "Fort Lauderdale Strikers", "flairClass": "NASL-FTL" },
    { "flairLabel": "Indy Eleven", "flairClass": "NASL-IND" },
    { "flairLabel": "Jacksonville Armada", "flairClass": "NASL-JAX" },
    { "flairLabel": "Miami FC", "flairClass": "NASL-MIA" },
    { "flairLabel": "Minnesota United", "flairClass": "NASL-MIN" },
    { "flairLabel": "New York Cosmos", "flairClass": "NASL-COS" },
    { "flairLabel": "Ottawa Fury", "flairClass": "NASL-OTT" },
    { "flairLabel": "Puerto Rico FC", "flairClass": "NASL-PRFC" },
    { "flairLabel": "Rayo OKC", "flairClass": "NASL-OKC" },
    { "flairLabel": "San Francisco Deltas", "flairClass": "NASL-SFD" },
    { "flairLabel": "Tampa Bay Rowdies", "flairClass": "NASL-TBR" }
]
USLFlairList = [
    { "flairLabel": "United Soccer League", "flairClass": "USL-USL" },
    { "flairLabel": "USL Pro", "flairClass": "USL-USL2" },
   
    { "flairLabel": "Arizona United SC", "flairClass": "USL-AZU" },
    { "flairLabel": "Austin Aztex", "flairClass": "USL-AAZ" },
    { "flairLabel": "Bethlehem Steel FC", "flairClass": "USL-BETH" },
    { "flairLabel": "Charleston Battery", "flairClass": "USL-BATT" },
    { "flairLabel": "Charlotte Independence", "flairClass": "USL-CIND" },
    { "flairLabel": "Colorado Springs Switchbacks FC", "flairClass": "USL-SWCH" },
    { "flairLabel": "FC Cincinnati", "flairClass": "USL-CINC" },
    { "flairLabel": "FC Montreal", "flairClass": "USL-MNRL" },
    { "flairLabel": "Harrisburg City Islanders", "flairClass": "USL-HCIL" },
    { "flairLabel": "LA Galaxy II", "flairClass": "USL-LAG2" },
    { "flairLabel": "Louisville City FC", "flairClass": "USL-LVC" },
    { "flairLabel": "New York Red Bulls II", "flairClass": "USL-NYRB2" },
    { "flairLabel": "OKC Energy FC", "flairClass": "USL-ONRG" },
    { "flairLabel": "Orange County Blues FC", "flairClass": "USL-OBLU" },
    { "flairLabel": "Orlando City B", "flairClass": "USL-ORLB" },
    { "flairLabel": "Pittsburgh Riverhounds", "flairClass": "USL-RIVR" },
    { "flairLabel": "Portland Timbers 2", "flairClass": "USL-POR2" },
    { "flairLabel": "Real Monarchs SLC", "flairClass": "USL-SLC2" },
    { "flairLabel": "Richmond Kickers", "flairClass": "USL-KIKR" },
    { "flairLabel": "Rio Grande Valley FC", "flairClass": "USL-RGV" },
    { "flairLabel": "Rochester Rhinos", "flairClass": "USL-RNOS" },
    { "flairLabel": "Sacramento Republic FC", "flairClass": "USL-SREP" },
    { "flairLabel": "Saint Louis FC", "flairClass": "USL-STLO" },
    { "flairLabel": "San Antonio FC", "flairClass": "USL-SAFC" },
    { "flairLabel": "Seattle Sounders FC 2", "flairClass": "USL-STL2" },
    { "flairLabel": "Swope Park Rangers KC", "flairClass": "USL-SPRKC" },
    { "flairLabel": "Toronto FC II", "flairClass": "USL-TFC2" },
    { "flairLabel": "Tulsa Roughnecks", "flairClass": "USL-TULR" },
    { "flairLabel": "Vancouver Whitecaps FC 2", "flairClass": "USL-VWC2" },
    { "flairLabel": "Wilmington Hammerheads FC", "flairClass": "USL-WHH" },
    
    { "flairLabel": "Antigua Barracuda FC", "flairClass": "USL-ANTB" },
    { "flairLabel": "Charlotte Eagles", "flairClass": "USL-CEGL" },
    { "flairLabel": "Dayton Dutch Lions", "flairClass": "USL-DDL" },
    { "flairLabel": "FC New York", "flairClass": "USL-FCNY" },
    { "flairLabel": "Orlando City SC", "flairClass": "USL-OCSC" },
    { "flairLabel": "Phoenix FC", "flairClass": "USL-PHXFC" },
    { "flairLabel": "Puerto Rico United", "flairClass": "USL-PRUTD" },
    { "flairLabel": "River Plate Puerto Rico", "flairClass": "USL-RPPR" },
    { "flairLabel": "Sevilla FC Puerto Rico", "flairClass": "USL-SEVPR" },
    { "flairLabel": "VSI Tampa Bay", "flairClass": "USL-VSIT" }
]
NPSLFlairList = [
    { "flairLabel": "National Premier Soccer League", "flairClass": "NPSL-NPSL" },
    { "flairLabel": "National Premier Soccer League", "flairClass": "NPSL-NPSL2" },

    { "flairLabel": "Boston City FC", "flairClass": "NPSL-BOSCFC" },
    { "flairLabel": "Brooklyn Italians", "flairClass": "NPSL-BROI" },
    { "flairLabel": "Greater Lowell United FC", "flairClass": "NPSL-GLUFC" },
    { "flairLabel": "Kingston Stockade FC", "flairClass": "NPSL-KSFC" },
    { "flairLabel": "New York Athletic Club", "flairClass": "NPSL-NYAC" },
    { "flairLabel": "New York Athletic Club", "flairClass": "NPSL-NYAC2" },
    { "flairLabel": "New York Cosmos B", "flairClass": "NPSL-COSB" },
    { "flairLabel": "Rhode Island Reds", "flairClass": "NPSL-RIRED" },
    { "flairLabel": "Seacoast United Mariners", "flairClass": "NPSL-SUMAR" },
    { "flairLabel": "Seacoast United Phantoms", "flairClass": "NPSL-SUPHA" },
    { "flairLabel": "Buxmont Torch FC", "flairClass": "NPSL-BTFC" },
    { "flairLabel": "Clarkstown Eagles SC", "flairClass": "NPSL-CESC" },
    { "flairLabel": "Electric City Shock SC", "flairClass": "NPSL-ECSCC" },
    { "flairLabel": "Greater Binghamton FC Thunder", "flairClass": "NPSL-GBFCT" },
    { "flairLabel": "Hershey FC", "flairClass": "NPSL-HERFC" },
    { "flairLabel": "Hershey FC", "flairClass": "NPSL-HERFC2" },
    { "flairLabel": "Jersey Blues FC", "flairClass": "NPSL-JBFC" },
    { "flairLabel": "Junior Lone Star FC", "flairClass": "NPSL-JLSFC" },
    { "flairLabel": "New Jersey Copa FC", "flairClass": "NPSL-NJCFC" },
    { "flairLabel": "ASA Charge", "flairClass": "NPSL-ASAC" },
    { "flairLabel": "Chesterfield United FC", "flairClass": "NPSL-CUFC" },
    { "flairLabel": "Chesterfield United FC", "flairClass": "NPSL-CUFC2" },
    { "flairLabel": "FC Frederick", "flairClass": "NPSL-FCRE" },
    { "flairLabel": "Fredericksburg FC", "flairClass": "NPSL-FREFC" },
    { "flairLabel": "Legacy 76", "flairClass": "NPSL-L76" },
    { "flairLabel": "Legacy 76", "flairClass": "NPSL-L762" },
    { "flairLabel": "Virginia Beach City FC", "flairClass": "NPSL-VBCFC" },
    { "flairLabel": "Atlanta Silverbacks FC", "flairClass": "NPSL-ASFC" },
    { "flairLabel": "Carolina Railhawks U-23", "flairClass": "NPSL-CRU23" },
    { "flairLabel": "FC Carolina Discoveries", "flairClass": "NPSL-FCCD" },
    { "flairLabel": "FC Carolina Discoveries", "flairClass": "NPSL-FCCD2" },
    { "flairLabel": "Georgia Revolution FC", "flairClass": "NPSL-GREVFC" },
    { "flairLabel": "Myrtle Beach Mutiny", "flairClass": "NPSL-MYRBM" },
    { "flairLabel": "Tobacco Road", "flairClass": "NPSL-TROAD" },
    { "flairLabel": "Corinthians FC of San Antonio", "flairClass": "NPSL-CFCSA" },
    { "flairLabel": "Dallas City FC", "flairClass": "NPSL-DALCFC" },
    { "flairLabel": "FC Wichita", "flairClass": "NPSL-FCWI" },
    { "flairLabel": "Fort Worth Vaqueros FC", "flairClass": "NPSL-FWVFC" },
    { "flairLabel": "Houston Regals SCA", "flairClass": "NPSL-HRSCA" },
    { "flairLabel": "Joplin Demize", "flairClass": "NPSL-JDFC" },
    { "flairLabel": "Little Rock Rangers", "flairClass": "NPSL-LRRFC" },
    { "flairLabel": "Liverpool Warriors", "flairClass": "NPSL-LPWFC" },
    { "flairLabel": "Shreveport Rafters FC", "flairClass": "NPSL-SRFC" },
    { "flairLabel": "Tulsa Athletics", "flairClass": "NPSL-TULA" },
    { "flairLabel": "Birmingham Hammers", "flairClass": "NPSL-BHAMM" },
    { "flairLabel": "Chattanooga FC", "flairClass": "NPSL-CHATFC" },
    { "flairLabel": "Knoxville Force", "flairClass": "NPSL-KXVFOR" },
    { "flairLabel": "Memphis City FC", "flairClass": "NPSL-MEMCFC" },
    { "flairLabel": "Nashville FC", "flairClass": "NPSL-NASHFC" },
    { "flairLabel": "New Orleans Jesters", "flairClass": "NPSL-NOLAJ" },
    { "flairLabel": "Fort Lauderdale Strikers", "flairClass": "NPSL-FTLS" },
    { "flairLabel": "Jacksonville United", "flairClass": "NPSL-JAXU" },
    { "flairLabel": "Kraze United", "flairClass": "NPSL-KRAZE" },
    { "flairLabel": "Miami Fusion", "flairClass": "NPSL-MIAFUS" },
    { "flairLabel": "Miami United FC", "flairClass": "NPSL-MIAUTD" },
    { "flairLabel": "Storm FC", "flairClass": "NPSL-STOFC" },
    { "flairLabel": "Tampa Bay Rowdies 2", "flairClass": "NPSL-TBR2" },
    { "flairLabel": "Weston FC", "flairClass": "NPSL-WESFC" },
    { "flairLabel": "AFC Cleveland", "flairClass": "NPSL-ACLEV" },
    { "flairLabel": "Erie Commodores", "flairClass": "NPSL-ERIC" },
    { "flairLabel": "FC Buffalo", "flairClass": "NPSL-FCBUF" },
    { "flairLabel": "FC Indiana", "flairClass": "NPSL-FCIND" },
    { "flairLabel": "Fort Pitt Regiment", "flairClass": "NPSL-FPREG" },
    { "flairLabel": "Indy Eleven NPSL", "flairClass": "NPSL-ID11" },
    { "flairLabel": "Rochester River Dogz", "flairClass": "NPSL-RDOGZ" },
    { "flairLabel": "AFC Ann Arbor", "flairClass": "NPSL-AFCAA" },
    { "flairLabel": "Dayton Dynamo", "flairClass": "NPSL-DAYD" },
    { "flairLabel": "Detroit City FC", "flairClass": "NPSL-DETCFC" },
    { "flairLabel": "Grand Rapids FC", "flairClass": "NPSL-GRAPFC" },
    { "flairLabel": "Kalamazoo FC", "flairClass": "NPSL-KALFC" },
    { "flairLabel": "Lansing United", "flairClass": "NPSL-LANU" },
    { "flairLabel": "Michigan Stars", "flairClass": "NPSL-MICHS" },
    { "flairLabel": "CD Aguiluchos USA", "flairClass": "NPSL-CDAU" },
    { "flairLabel": "Real San Jose", "flairClass": "NPSL-REALSJ" },
    { "flairLabel": "Sacramento Gold", "flairClass": "NPSL-SACG" },
    { "flairLabel": "San Francisco Stompers", "flairClass": "NPSL-SFRAS" },
    { "flairLabel": "Sonoma County Sol", "flairClass": "NPSL-SCSOL" },
    { "flairLabel": "OSA FC", "flairClass": "NPSL-OSAFC" },
    { "flairLabel": "Spartans FC", "flairClass": "NPSL-SPAFC" },
    { "flairLabel": "Albion FC", "flairClass": "NPSL-ALBFC" },
    { "flairLabel": "Deportivo Coras USA U-23", "flairClass": "NPSL-DCORU" },
    { "flairLabel": "FC Hasental", "flairClass": "NPSL-FCHAS" },
    { "flairLabel": "North County Battalion", "flairClass": "NPSL-NCBAT" },
    { "flairLabel": "Southern California Sports Club", "flairClass": "NPSL-SCALSC" },
    { "flairLabel": "Sports Club Corinthians USA", "flairClass": "NPSL-SCCUSA" },
    { "flairLabel": "Temecula FC", "flairClass": "NPSL-TEMFC" }
]

FlairList = MLSFlairList + NASLFlairList + USLFlairList + NPSLFlairList