structureStatuses = [
{ "id" : "1", "status" : "Active" }, 
{ "id" : "2", "status" : "Inactive" },
]

flairs = [
{ "flairLabel" : "Major League Soccer", "flairClass" : "MLS-MLS" },
{ "flairLabel" : "Major League Soccer", "flairClass" : "MLS-MLS2" },
{ "flairLabel" : "Atlanta United FC", "flairClass" : "MLS-ATL" },
{ "flairLabel" : "Chicago Fire", "flairClass" : "MLS-CHI" },
{ "flairLabel" : "Colorado Rapids", "flairClass" : "MLS-COL" },
{ "flairLabel" : "Columbus Crew", "flairClass" : "MLS-CLB" },
{ "flairLabel" : "DC United", "flairClass" : "MLS-DCU" },
{ "flairLabel" : "FC Dallas", "flairClass" : "MLS-DAL" },
{ "flairLabel" : "Houston Dynamo", "flairClass" : "MLS-HOU" },
{ "flairLabel" : "LA Galaxy", "flairClass" : "MLS-LAG" },
{ "flairLabel" : "Los Angeles FC", "flairClass" : "MLS-LAFC" },
{ "flairLabel" : "Montreal Impact", "flairClass" : "MLS-MTL" },
{ "flairLabel" : "New England Revolution", "flairClass" : "MLS-NER" },
{ "flairLabel" : "New York Red Bulls", "flairClass" : "MLS-NYRB" },
{ "flairLabel" : "New York City FC", "flairClass" : "MLS-NYCFC" },
{ "flairLabel" : "Orlando City", "flairClass" : "MLS-OCSC" },
{ "flairLabel" : "Philadelphia Union", "flairClass" : "MLS-PHI" },
{ "flairLabel" : "Portland Timbers", "flairClass" : "MLS-POR" },
{ "flairLabel" : "Real Salt Lake", "flairClass" : "MLS-RSL" },
{ "flairLabel" : "Seattle Sounders", "flairClass" : "MLS-SEA" },
{ "flairLabel" : "Sporting Kansas City", "flairClass" : "MLS-SKC" },
{ "flairLabel" : "Toronto FC", "flairClass" : "MLS-TOR" },
{ "flairLabel" : "Vancouver Whitecaps", "flairClass" : "MLS-VWC" },
{ "flairLabel" : "North American Soccer League", "flairClass" : "NASL-NASL" },
{ "flairLabel" : "Atlanta Silverbacks", "flairClass" : "NASL-ATL" },
{ "flairLabel" : "Carolina Railhawks", "flairClass" : "NASL-CAR" },
{ "flairLabel" : "FC Edmonton", "flairClass" : "NASL-FCE" },
{ "flairLabel" : "Fort Lauderdale Strikers", "flairClass" : "NASL-FTL" },
{ "flairLabel" : "Indy Eleven", "flairClass" : "NASL-IND" },
{ "flairLabel" : "Jacksonville Armada", "flairClass" : "NASL-JAX" },
{ "flairLabel" : "Miami FC", "flairClass" : "NASL-MIA" },
{ "flairLabel" : "Minnesota United", "flairClass" : "NASL-MIN" },
{ "flairLabel" : "New York Cosmos", "flairClass" : "NASL-COS" },
{ "flairLabel" : "Ottawa Fury", "flairClass" : "NASL-OTT" },
{ "flairLabel" : "Puerto Rico FC", "flairClass" : "NASL-PRFC" },
{ "flairLabel" : "Rayo OKC", "flairClass" : "NASL-OKC" },
{ "flairLabel" : "San Antonio Scorpions", "flairClass" : "NASL-SAS" },
{ "flairLabel" : "San Francisco Deltas", "flairClass" : "NASL-SFD" },
{ "flairLabel" : "Tampa Bay Rowdies", "flairClass" : "NASL-TBR" },
{ "flairLabel" : "United Soccer League", "flairClass" : "USL-USL" },
{ "flairLabel" : "USL Pro", "flairClass" : "USL-USL2",},
{ "flairLabel" : "Arizona United SC", "flairClass" : "USL-AZU" },
{ "flairLabel" : "Austin Aztex", "flairClass" : "USL-AAZ" },
{ "flairLabel" : "Bethlehem Steel FC", "flairClass" : "USL-BETH" },
{ "flairLabel" : "Charleston Battery", "flairClass" : "USL-BATT" },
{ "flairLabel" : "Charlotte Independence", "flairClass" : "USL-CIND" },
{ "flairLabel" : "Colorado Springs Switchbacks FC", "flairClass" : "USL-SWCH" },
{ "flairLabel" : "FC Cincinnati", "flairClass" : "USL-CINC" },
{ "flairLabel" : "FC Montreal", "flairClass" : "USL-MNRL" },
{ "flairLabel" : "Harrisburg City Islanders", "flairClass" : "USL-HCIL" },
{ "flairLabel" : "LA Galaxy II", "flairClass" : "USL-LAG2" },
{ "flairLabel" : "Louisville City FC", "flairClass" : "USL-LVC" },
{ "flairLabel" : "New York Red Bulls II", "flairClass" : "USL-NYRB2" },
{ "flairLabel" : "OKC Energy FC", "flairClass" : "USL-ONRG" },
{ "flairLabel" : "Orange County Blues FC", "flairClass" : "USL-OBLU" },
{ "flairLabel" : "Orlando City B", "flairClass" : "USL-ORLB" },
{ "flairLabel" : "Pittsburgh Riverhounds", "flairClass" : "USL-RIVR" },
{ "flairLabel" : "Portland Timbers 2", "flairClass" : "USL-POR2" },
{ "flairLabel" : "Real Monarchs SLC", "flairClass" : "USL-SLC2" },
{ "flairLabel" : "Richmond Kickers", "flairClass" : "USL-KIKR" },
{ "flairLabel" : "Rio Grande Valley FC", "flairClass" : "USL-RGV" },
{ "flairLabel" : "Rochester Rhinos", "flairClass" : "USL-RNOS" },
{ "flairLabel" : "Sacramento Republic FC", "flairClass" : "USL-SREP" },
{ "flairLabel" : "Saint Louis FC", "flairClass" : "USL-STLO" },
{ "flairLabel" : "San Antonio FC", "flairClass" : "USL-SAFC" },
{ "flairLabel" : "Seattle Sounders FC 2", "flairClass" : "USL-STL2" },
{ "flairLabel" : "Swope Park Rangers KC", "flairClass" : "USL-SPRKC" },
{ "flairLabel" : "Toronto FC II", "flairClass" : "USL-TFC2" },
{ "flairLabel" : "Tulsa Roughnecks", "flairClass" : "USL-TULR" },
{ "flairLabel" : "Vancouver Whitecaps FC 2", "flairClass" : "USL-VWC2" },
{ "flairLabel" : "Wilmington Hammerheads FC", "flairClass" : "USL-WHH" },
{ "flairLabel" : "Antigua Barracuda FC", "flairClass" : "USL-ANTB" },
{ "flairLabel" : "Charlotte Eagles", "flairClass" : "USL-CEGL" },
{ "flairLabel" : "Dayton Dutch Lions", "flairClass" : "USL-DDL" },
{ "flairLabel" : "FC New York", "flairClass" : "USL-FCNY" },
{ "flairLabel" : "Orlando City SC", "flairClass" : "USL-OCSC" },
{ "flairLabel" : "Phoenix FC", "flairClass" : "USL-PHXFC" },
{ "flairLabel" : "Puerto Rico United", "flairClass" : "USL-PRUTD" },
{ "flairLabel" : "River Plate Puerto Rico", "flairClass" : "USL-RPPR" },
{ "flairLabel" : "Sevilla FC Puerto Rico", "flairClass" : "USL-SEVPR" },
{ "flairLabel" : "VSI Tampa Bay", "flairClass" : "USL-VSIT" },
{ "flairLabel" : "National Premier Soccer League", "flairClass" : "NPSL-NPSL" },
{ "flairLabel" : "National Premier Soccer League", "flairClass" : "NPSL-NPSL2" },
{ "flairLabel" : "Boston City FC", "flairClass" : "NPSL-BOSCFC" },
{ "flairLabel" : "Brooklyn Italians", "flairClass" : "NPSL-BROI" },
{ "flairLabel" : "Greater Lowell United FC", "flairClass" : "NPSL-GLUFC" },
{ "flairLabel" : "Kingston Stockade FC", "flairClass" : "NPSL-KSFC" },
{ "flairLabel" : "New York Athletic Club", "flairClass" : "NPSL-NYAC" },
{ "flairLabel" : "New York Athletic Club", "flairClass" : "NPSL-NYAC2" },
{ "flairLabel" : "New York Cosmos B", "flairClass" : "NPSL-COSB" },
{ "flairLabel" : "Rhode Island Reds", "flairClass" : "NPSL-RIRED" },
{ "flairLabel" : "Seacoast United Mariners", "flairClass" : "NPSL-SUMAR" },
{ "flairLabel" : "Seacoast United Phantoms", "flairClass" : "NPSL-SUPHA" },
{ "flairLabel" : "Buxmont Torch FC", "flairClass" : "NPSL-BTFC" },
{ "flairLabel" : "Clarkstown Eagles SC", "flairClass" : "NPSL-CESC" },
{ "flairLabel" : "Electric City Shock SC", "flairClass" : "NPSL-ECSCC" },
{ "flairLabel" : "Greater Binghamton FC Thunder", "flairClass" : "NPSL-GBFCT" },
{ "flairLabel" : "Hershey FC", "flairClass" : "NPSL-HERFC" },
{ "flairLabel" : "Hershey FC", "flairClass" : "NPSL-HERFC2" },
{ "flairLabel" : "Jersey Blues FC", "flairClass" : "NPSL-JBFC" },
{ "flairLabel" : "Junior Lone Star FC", "flairClass" : "NPSL-JLSFC" },
{ "flairLabel" : "New Jersey Copa FC", "flairClass" : "NPSL-NJCFC" },
{ "flairLabel" : "ASA Charge", "flairClass" : "NPSL-ASAC" },
{ "flairLabel" : "Chesterfield United FC", "flairClass" : "NPSL-CUFC" },
{ "flairLabel" : "Chesterfield United FC", "flairClass" : "NPSL-CUFC2" },
{ "flairLabel" : "FC Frederick", "flairClass" : "NPSL-FCRE" },
{ "flairLabel" : "Fredericksburg FC", "flairClass" : "NPSL-FREFC" },
{ "flairLabel" : "Legacy 76", "flairClass" : "NPSL-L76" },
{ "flairLabel" : "Legacy 76", "flairClass" : "NPSL-L762" },
{ "flairLabel" : "Virginia Beach City FC", "flairClass" : "NPSL-VBCFC" },
{ "flairLabel" : "Atlanta Silverbacks FC", "flairClass" : "NPSL-ASFC" },
{ "flairLabel" : "Carolina Railhawks U-23", "flairClass" : "NPSL-CRU23" },
{ "flairLabel" : "FC Carolina Discoveries", "flairClass" : "NPSL-FCCD" },
{ "flairLabel" : "FC Carolina Discoveries", "flairClass" : "NPSL-FCCD2" },
{ "flairLabel" : "Georgia Revolution FC", "flairClass" : "NPSL-GREVFC" },
{ "flairLabel" : "Myrtle Beach Mutiny", "flairClass" : "NPSL-MYRBM" },
{ "flairLabel" : "Tobacco Road", "flairClass" : "NPSL-TROAD" },
{ "flairLabel" : "Corinthians FC of San Antonio", "flairClass" : "NPSL-CFCSA" },
{ "flairLabel" : "Dallas City FC", "flairClass" : "NPSL-DALCFC" },
{ "flairLabel" : "FC Wichita", "flairClass" : "NPSL-FCWI" },
{ "flairLabel" : "Fort Worth Vaqueros FC", "flairClass" : "NPSL-FWVFC" },
{ "flairLabel" : "Houston Regals SCA", "flairClass" : "NPSL-HRSCA" },
{ "flairLabel" : "Joplin Demize", "flairClass" : "NPSL-JDFC" },
{ "flairLabel" : "Little Rock Rangers", "flairClass" : "NPSL-LRRFC" },
{ "flairLabel" : "Liverpool Warriors", "flairClass" : "NPSL-LPWFC" },
{ "flairLabel" : "Shreveport Rafters FC", "flairClass" : "NPSL-SRFC" },
{ "flairLabel" : "Tulsa Athletics", "flairClass" : "NPSL-TULA" },
{ "flairLabel" : "Birmingham Hammers", "flairClass" : "NPSL-BHAMM" },
{ "flairLabel" : "Chattanooga FC", "flairClass" : "NPSL-CHATFC" },
{ "flairLabel" : "Knoxville Force", "flairClass" : "NPSL-KXVFOR" },
{ "flairLabel" : "Memphis City FC", "flairClass" : "NPSL-MEMCFC" },
{ "flairLabel" : "Nashville FC", "flairClass" : "NPSL-NASHFC" },
{ "flairLabel" : "New Orleans Jesters", "flairClass" : "NPSL-NOLAJ" },
{ "flairLabel" : "Fort Lauderdale Strikers", "flairClass" : "NPSL-FTLS" },
{ "flairLabel" : "Jacksonville United", "flairClass" : "NPSL-JAXU" },
{ "flairLabel" : "Kraze United", "flairClass" : "NPSL-KRAZE" },
{ "flairLabel" : "Miami Fusion", "flairClass" : "NPSL-MIAFUS" },
{ "flairLabel" : "Miami United FC", "flairClass" : "NPSL-MIAUTD" },
{ "flairLabel" : "Storm FC", "flairClass" : "NPSL-STOFC" },
{ "flairLabel" : "Tampa Bay Rowdies 2", "flairClass" : "NPSL-TBR2" },
{ "flairLabel" : "Weston FC", "flairClass" : "NPSL-WESFC" },
{ "flairLabel" : "AFC Cleveland", "flairClass" : "NPSL-ACLEV" },
{ "flairLabel" : "Erie Commodores", "flairClass" : "NPSL-ERIC" },
{ "flairLabel" : "FC Buffalo", "flairClass" : "NPSL-FCBUF" },
{ "flairLabel" : "FC Indiana", "flairClass" : "NPSL-FCIND" },
{ "flairLabel" : "Fort Pitt Regiment", "flairClass" : "NPSL-FPREG" },
{ "flairLabel" : "Indy Eleven NPSL", "flairClass" : "NPSL-ID11" },
{ "flairLabel" : "Rochester River Dogz", "flairClass" : "NPSL-RDOGZ" },
{ "flairLabel" : "AFC Ann Arbor", "flairClass" : "NPSL-AFCAA" },
{ "flairLabel" : "Dayton Dynamo", "flairClass" : "NPSL-DAYD" },
{ "flairLabel" : "Detroit City FC", "flairClass" : "NPSL-DETCFC" },
{ "flairLabel" : "Grand Rapids FC", "flairClass" : "NPSL-GRAPFC" },
{ "flairLabel" : "Kalamazoo FC", "flairClass" : "NPSL-KALFC" },
{ "flairLabel" : "Lansing United", "flairClass" : "NPSL-LANU" },
{ "flairLabel" : "Michigan Stars", "flairClass" : "NPSL-MICHS" },
{ "flairLabel" : "CD Aguiluchos USA", "flairClass" : "NPSL-CDAU" },
{ "flairLabel" : "Real San Jose", "flairClass" : "NPSL-REALSJ" },
{ "flairLabel" : "Sacramento Gold", "flairClass" : "NPSL-SACG" },
{ "flairLabel" : "San Francisco Stompers", "flairClass" : "NPSL-SFRAS" },
{ "flairLabel" : "Sonoma County Sol", "flairClass" : "NPSL-SCSOL" },
{ "flairLabel" : "OSA FC", "flairClass" : "NPSL-OSAFC" },
{ "flairLabel" : "Spartans FC", "flairClass" : "NPSL-SPAFC" },
{ "flairLabel" : "Albion SC Pros", "flairClass" : "NPSL-ALBFC" },
{ "flairLabel" : "Deportivo Coras USA U-23", "flairClass" : "NPSL-DCORU" },
{ "flairLabel" : "FC Hasental", "flairClass" : "NPSL-FCHAS" },
{ "flairLabel" : "North County Battalion", "flairClass" : "NPSL-NCBAT" },
{ "flairLabel" : "Southern California Sports Club", "flairClass" : "NPSL-SCALSC" },
{ "flairLabel" : "Corinthians USA", "flairClass" : "NPSL-SCCUSA" },
{ "flairLabel" : "Temecula FC", "flairClass" : "NPSL-TEMFC" }
]

leagues = [
{ "id" : "1", "name" : "Major League Soccer", "abbreviation" : "MLS", "flairClass" : "MLS-MLS", "statusId" : "1" },
{ "id" : "2", "name" : "North American Soccer League", "abbreviation" : "NASL", "flairClass" : "NASL-NASL", "statusId" : "1" },
{ "id" : "3", "name" : "United Soccer League", "abbreviation" : "USL", "flairClass" : "USL-USL", "statusId" : "1" },
{ "id" : "4", "name" : "National Premier Soccer League", "abbreviation" : "NPSL", "flairClass" : "NPSL-NPSL", "statusId" : "1" },
{ "id" : "5", "name" : "National Womens Soccer League", "abbreviation" : "NWSL", "flairClass" : "NWSL-NWSL", "statusId" : "1" }
]

regions = [
{ "id" : "1", "name" : "Northeast Region", "abbreviation" : "NER", "flairClass" : "", "leagueId" : "4", "statusId" : "1" },
{ "id" : "2", "name" : "South Region", "abbreviation" : "SR", "flairClass" : "", "leagueId" : "4", "statusId" : "1" },
{ "id" : "3", "name" : "Midwest Region", "abbreviation" : "MWR", "flairClass" : "", "leagueId": "4", "statusId" : "1" },
{ "id" : "4", "name" : "West Region", "abbreviation" : "WR", "flairClass" : "", "leagueId": "4", "statusId" : "1" },
]

conferences = [
{ "id" : "1", "name" : "Eastern Conference", "abbreviation" : "EC", "flairClass" : "", "leagueId" : "1", "regionId" : "", "statusId" : "1" },
{ "id" : "2", "name" : "Western Conference", "abbreviation" : "WC", "flairClass" : "", "leagueId" : "1",  "regionId" : "", "statusId" : "1" },
{ "id" : "3", "name" : "Eastern Conference", "abbreviation" : "EC", "flairClass" : "", "leagueId" : "3",  "regionId" : "", "statusId" : "1" },
{ "id" : "4", "name" : "Western Conference", "abbreviation" : "WC", "flairClass" : "", "leagueId" : "3",  "regionId" : "", "statusId" : "1" },
{ "id" : "5", "name" : "Atlantic Conference", "abbreviation" : "ATL", "flairClass" : "", "leagueId" : "4", "regionId" : "1", "statusId" : "1" },
{ "id" : "6", "name" : "Keystone Conference", "abbreviation" : "KEY", "flairClass" : "", "leagueId" : "4", "regionId" : "1", "statusId" : "1" },
{ "id" : "7", "name" : "Mid-Atlantic Conference", "abbreviation" : "MATL", "flairClass" : "", "leagueId" : "4", "regionId" : "1", "statusId" : "1" },
{ "id" : "8", "name" : "South Atlantic Conference", "abbreviation" : "SATL", "flairClass" : "", "leagueId" : "4", "regionId" : "2", "statusId" : "1" },
{ "id" : "9", "name" : "South Central Conference", "abbreviation" : "SCTL", "flairClass" : "", "leagueId" : "4", "regionId" : "2", "statusId" : "1" },
{ "id" : "10", "name" : "Southeast Conference", "abbreviation" : "SEAST", "flairClass" : "", "leagueId" : "4", "regionId" : "2", "statusId" : "1" },
{ "id" : "11", "name" : "Sunshine Conference", "abbreviation" : "SUN", "flairClass" : "", "leagueId" : "4", "regionId" : "2", "statusId" : "1" },
{ "id" : "12", "name" : "Great Lakes East Conference", "abbreviation" : "GLEAST", "flairClass" : "", "leagueId" : "4", "regionId" : "3", "statusId" : "1" },
{ "id" : "13", "name" : "Great Lakes West Conference", "abbreviation" : "GLWEST", "flairClass" : "", "leagueId" : "4", "regionId" : "3", "statusId" : "1" },
{ "id" : "14", "name" : "Central Conference (provisional)", "abbreviation" : "CTL", "flairClass" : "", "leagueId" : "4", "regionId" : "3", "statusId" : "1" },
{ "id" : "15", "name" : "Golden Gate Conference", "abbreviation" : "GGATE", "flairClass" : "", "leagueId" : "4", "regionId" : "4", "statusId" : "1" },
{ "id" : "16", "name" : "Northwest Conference", "abbreviation" : "NW", "flairClass" : "", "leagueId" : "4", "regionId" : "4", "statusId" : "1" },
{ "id" : "17", "name" : "Southwest Conference", "abbreviation" : "SW", "flairClass" : "", "leagueId" : "4", "regionId" : "4", "statusId" : "1" }
]


teams = [
##MLS##
{ "name" : "Atlanta United FC", "abbreviation" : "ATL", "flairClass" : "MLS-ATL", "leagueId" : "1", "regionId" : "", "conferenceId" : "1", "divisionId" : "", "statusId" : "2" },
{ "name" : "Chicago Fire", "abbreviation" : "CHI", "flairClass" : "MLS-CHI", "leagueId" : "1", "regionId" : "", "conferenceId" : "1", "divisionId" : "", "statusId" : "1" },
{ "name" : "Chivas USA", "abbreviation" : "CVS", "flairClass" : "MLS-CVS", "leagueId" : "1", "regionId" : "", "conferenceId" : "2", "divisionId" : "", "statusId" : "2" },
{ "name" : "Colorado Rapids", "abbreviation" : "COL", "flairClass" : "MLS-COL", "leagueId" : "1", "regionId" : "", "conferenceId" : "1", "divisionId" : "", "statusId" : "1" },
{ "name" : "Columbus Crew", "abbreviation" : "CLB", "flairClass" : "MLS-CLB", "leagueId" : "1", "regionId" : "", "conferenceId" : "1", "divisionId" : "", "statusId" : "1" },
{ "name" : "DC United", "abbreviation" : "DCU", "flairClass" : "MLS-DCU", "leagueId" : "1", "regionId" : "", "conferenceId" : "1", "divisionId" : "", "statusId" : "1" },
{ "name" : "FC Dallas", "abbreviation" : "DAL", "flairClass" : "MLS-DAL", "leagueId" : "1", "regionId" : "", "conferenceId" : "2", "divisionId" : "", "statusId" : "1" },
{ "name" : "Houston Dynamo", "abbreviation" : "HOU", "flairClass" : "MLS-Southwest Conference", "leagueId" : "1", "regionId" : "", "conferenceId" : "2", "divisionId" : "", "statusId" : "1" },
{ "name" : "LA Galaxy", "abbreviation" : "LAG", "flairClass" : "MLS-LAG", "leagueId" : "1", "regionId" : "", "conferenceId" : "2", "divisionId" : "", "statusId" : "1" },
{ "name" : "Los Angeles FC", "abbreviation" : "LAFC", "flairClass" : "MLS-LAFC", "leagueId" : "1", "regionId" : "", "conferenceId" : "2", "divisionId" : "", "statusId" : "2" },
{ "name" : "Miami MLS", "abbreviation" : "MIA", "flairClass" : "MLS-MIA", "leagueId" : "1", "regionId" : "", "conferenceId" : "1", "divisionId" : "", "statusId" : "2" },
{ "name" : "Miami Fusion", "abbreviation" : "MIA", "flairClass" : "MLS-MIAF", "leagueId" : "1", "regionId" : "", "conferenceId" : "1", "divisionId" : "", "statusId" : "2" },
{ "name" : "Minnesota United FC", "abbreviation" : "MIN", "flairClass" : "MLS-MIN", "leagueId" : "1", "regionId" : "", "conferenceId" : "1", "divisionId" : "", "statusId" : "2" },
{ "name" : "Montreal Impact", "abbreviation" : "MTL", "flairClass" : "MLS-MTL", "leagueId" : "1", "regionId" : "", "conferenceId" : "1", "divisionId" : "", "statusId" : "1" },
{ "name" : "New England Revolution", "abbreviation" : "NER", "flairClass" : "MLS-NER", "leagueId" : "1", "regionId" : "", "conferenceId" : "1", "divisionId" : "", "statusId" : "1" },
{ "name" : "New York Red Bulls", "abbreviation" : "NYRB", "flairClass" : "MLS-NYRB", "leagueId" : "1", "regionId" : "", "conferenceId" : "1", "divisionId" : "", "statusId" : "1" },
{ "name" : "New York City FC", "abbreviation" : "NYC", "flairClass" : "MLS-NYCFC", "leagueId" : "1", "regionId" : "", "conferenceId" : "1", "divisionId" : "", "statusId" : "1" },
{ "name" : "Orlando City SC", "abbreviation" : "ORL", "flairClass" : "MLS-ORL", "leagueId" : "1", "regionId" : "", "conferenceId" : "1", "divisionId" : "", "statusId" : "1" },
{ "name" : "Philadelphia Union", "abbreviation" : "PHI", "flairClass" : "MLS-PHI", "leagueId" : "1", "regionId" : "", "conferenceId" : "1", "divisionId" : "", "statusId" : "1" },
{ "name" : "Portland Timbers", "abbreviation" : "POR", "flairClass" : "MLS-POR", "leagueId" : "1", "regionId" : "", "conferenceId" : "2", "divisionId" : "", "statusId" : "1" },
{ "name" : "Real Salt Lake", "abbreviation" : "RSL", "flairClass" : "MLS-RSL", "leagueId" : "1", "regionId" : "", "conferenceId" : "2", "divisionId" : "", "statusId" : "1" },
{ "name" : "Seattle Sounders", "abbreviation" : "SEA", "flairClass" : "MLS-SEA", "leagueId" : "1", "regionId" : "", "conferenceId" : "2", "divisionId" : "", "statusId" : "1" },
{ "name" : "Sporting Kansas City", "abbreviation" : "SKC", "flairClass" : "MLS-SKC", "leagueId" : "1", "regionId" : "", "conferenceId" : "2", "divisionId" : "", "statusId" : "1" },
{ "name" : "Tampa Bay Mutiny", "abbreviation" : "TBM", "flairClass" : "MLS-TBM", "leagueId" : "1", "regionId" : "", "conferenceId" : "1", "divisionId" : "", "statusId" : "2" },
{ "name" : "Toronto FC", "abbreviation" : "TOR", "flairClass" : "MLS-TFC", "leagueId" : "1", "regionId" : "", "conferenceId" : "1", "divisionId" : "", "statusId" : "1" },
{ "name" : "Vancouver Whitecaps", "abbreviation" : "VAN", "flairClass" : "MLS-VWC", "leagueId" : "1", "regionId" : "", "conferenceId" : "2", "divisionId" : "", "statusId" : "1" },
##NASL##
{ "name" : "Atlanta Silverbacks", "abbreviation" : "ATL", "flairClass" : "NASL-ATL", "leagueId" : "2", "regionId" : "", "conferenceId" : "", "divisionId" : "", "statusId" : "2" },
{ "name" : "Carolina Railhawks", "abbreviation" : "CAR", "flairClass" : "NASL-CAR", "leagueId" : "2", "regionId" : "", "conferenceId" : "", "divisionId" : "", "statusId" : "1" },
{ "name" : "FC Edmonton", "abbreviation" : "FCE", "flairClass" : "NASL-FCE", "leagueId" : "2", "regionId" : "", "conferenceId" : "", "divisionId" : "", "statusId" : "1" },
{ "name" : "Fort Lauderdale Strikers", "abbreviation" : "FTL", "flairClass" : "NASL-FTL", "leagueId" : "2", "regionId" : "", "conferenceId" : "", "divisionId" : "", "statusId" : "1" },
{ "name" : "Indy Eleven", "abbreviation" : "IND", "flairClass" : "NASL-IND", "leagueId" : "2", "regionId" : "", "conferenceId" : "", "divisionId" : "", "statusId" : "1" },
{ "name" : "Jacksonville Armada", "abbreviation" : "JAX", "flairClass" : "NASL-JAX", "leagueId" : "2", "regionId" : "", "conferenceId" : "", "divisionId" : "", "statusId" : "1" },
{ "name" : "Miami FC", "abbreviation" : "MIA", "flairClass" : "NASL-MIA", "leagueId" : "2", "regionId" : "", "conferenceId" : "", "divisionId" : "", "statusId" : "1" },
{ "name" : "Montreal Impact", "abbreviation" : "MTL", "flairClass" : "NASL-MTL", "leagueId" : "2", "regionId" : "", "conferenceId" : "", "divisionId" : "", "statusId" : "2" },
{ "name" : "Minnesota United", "abbreviation" : "MNU", "flairClass" : "NASL-MNU", "leagueId" : "2", "regionId" : "", "conferenceId" : "", "divisionId" : "", "statusId" : "1" },
{ "name" : "New York Cosmos", "abbreviation" : "NYC", "flairClass" : "NASL-COS", "leagueId" : "2", "regionId" : "", "conferenceId" : "", "divisionId" : "", "statusId" : "1" },
{ "name" : "Ottawa Fury", "abbreviation" : "OTT", "flairClass" : "NASL-OTT", "leagueId" : "2", "regionId" : "", "conferenceId" : "", "divisionId" : "", "statusId" : "1" },
{ "name" : "Puerto Rico FC", "abbreviation" : "PRI", "flairClass" : "NASL-PRFC", "leagueId" : "2", "regionId" : "", "conferenceId" : "", "divisionId" : "", "statusId" : "1" },
{ "name" : "Puerto Rico Islanders", "abbreviation" : "PRI", "flairClass" : "NASL-PRIS", "leagueId" : "2", "regionId" : "", "conferenceId" : "", "divisionId" : "", "statusId" : "2" },
{ "name" : "Rayo OKC", "abbreviation" : "OKC", "flairClass" : "NASL-OKC", "leagueId" : "2", "regionId" : "", "conferenceId" : "", "divisionId" : "", "statusId" : "1" },
{ "name" : "Tampa Bay Rowdies", "abbreviation" : "TBR", "flairClass" : "NASL-TBR", "leagueId" : "2", "regionId" : "", "conferenceId" : "", "divisionId" : "", "statusId" : "1" },
{ "name" : "San Antonio Scorpions", "abbreviation" : "SAS", "flairClass" : "NASL-SAS", "leagueId" : "2", "regionId" : "", "conferenceId" : "", "divisionId" : "", "statusId" : "2" },
{ "name" : "San Francisco Deltas", "abbreviation" : "SFO", "flairClass" : "NASL-SFD", "leagueId" : "2", "regionId" : "", "conferenceId" : "", "divisionId" : "", "statusId" : "2" },
##USL##
{ "name" : "Antigua Barracuda FC", "abbreviation" : "ANT", "flairClass" : "USL-ANTB", "leagueId" : "3", "regionId" : "", "conferenceId" : "3", "divisionId" : "", "statusId" : "2" },
{ "name" : "Arizona United SC", "abbreviation" : "AZU", "flairClass" : "USL-AZU", "leagueId" : "3", "regionId" : "", "conferenceId" : "4", "divisionId" : "", "statusId" : "1" },
{ "name" : "Austin Aztex", "abbreviation" : "AUS", "flairClass" : "USL-AAZ", "leagueId" : "3", "regionId" : "", "conferenceId" : "4", "divisionId" : "", "statusId" : "2" },
{ "name" : "Bethlehem Steel FC", "abbreviation" : "BST", "flairClass" : "USL-BETH", "leagueId" : "3", "regionId" : "", "conferenceId" : "3", "divisionId" : "", "statusId" : "1" },
{ "name" : "Charleston Battery", "abbreviation" : "CHS", "flairClass" : "USL-BATT", "leagueId" : "3", "regionId" : "", "conferenceId" : "3", "divisionId" : "", "statusId" : "1" },
{ "name" : "Charlotte Eagles",  "abbreviation" : "CHL", "flairClass" : "USL-CEGL", "leagueId" : "3", "regionId" : "", "conferenceId" : "3", "divisionId" : "", "statusId" : "2" },
{ "name" : "Charlotte Independence", "abbreviation" : "CLT", "flairClass" : "USL-CIND", "leagueId" : "3", "regionId" : "", "conferenceId" : "3", "divisionId" : "", "statusId" : "1" },
{ "name" : "Colorado Springs Switchbacks FC", "abbreviation" : "COS", "flairClass" : "USL-SWCH", "leagueId" : "3", "regionId" : "", "conferenceId" : "4", "divisionId" : "", "statusId" : "1" },
{ "name" : "Dayton Dutch Lions",  "abbreviation" : "DAY", "flairClass" : "USL-DDL", "leagueId" : "3", "regionId" : "", "conferenceId" : "3", "divisionId" : "", "statusId" : "2" },
{ "name" : "FC Cincinnati", "abbreviation" : "CIN", "flairClass" : "USL-CINC", "leagueId" : "3", "regionId" : "", "conferenceId" : "3", "divisionId" : "", "statusId" : "1" },
{ "name" : "FC New York",  "abbreviation" : "FCNY", "flairClass" : "USL-FCNY", "leagueId" : "3", "regionId" : "", "conferenceId" : "3", "divisionId" : "", "statusId" : "2" },
{ "name" : "FC Montreal", "abbreviation" : "MTL", "flairClass" : "USL-MNRL", "leagueId" : "3", "regionId" : "", "conferenceId" : "3", "divisionId" : "", "statusId" : "1" },
{ "name" : "Harrisburg City Islanders", "abbreviation" : "HAR", "flairClass" : "USL-HCIL", "leagueId" : "3", "regionId" : "", "conferenceId" : "3", "divisionId" : "", "statusId" : "1" },
{ "name" : "LA Galaxy II", "abbreviation" : "LAG2", "flairClass" : "USL-LAG2", "leagueId" : "3", "regionId" : "", "conferenceId" : "4", "divisionId" : "", "statusId" : "1" },
{ "name" : "Louisville City FC", "abbreviation" : "LOU", "flairClass" : "USL-LVC", "leagueId" : "3", "regionId" : "", "conferenceId" : "4", "divisionId" : "", "statusId" : "1" },
{ "name" : "New York Red Bulls II", "abbreviation" : "NYRB2", "flairClass" : "USL-NYRB2", "leagueId" : "3", "regionId" : "", "conferenceId" : "3", "divisionId" : "", "statusId" : "1" },
{ "name" : "Oklahoma City Energy FC", "abbreviation" : "OKC", "flairClass" : "USL-ONRG", "leagueId" : "3", "regionId" : "", "conferenceId" : "4", "divisionId" : "", "statusId" : "1" },
{ "name" : "Orange County Blues FC", "abbreviation" : "OCB", "flairClass" : "USL-OBLU", "leagueId" : "3", "regionId" : "", "conferenceId" : "4", "divisionId" : "", "statusId" : "1" },
{ "name" : "Orlando City B", "abbreviation" : "ORLB", "flairClass" : "USL-ORLB", "leagueId" : "3", "regionId" : "", "conferenceId" : "3", "divisionId" : "", "statusId" : "1" },
{ "name" : "Orlando City SC",  "abbreviation" : "ORL", "flairClass" : "USL-OCSC", "leagueId" : "3", "regionId" : "", "conferenceId" : "3", "divisionId" : "", "statusId" : "2" },
{ "name" : "Phoenix FC",  "abbreviation" : "PHX", "flairClass" : "USL-PHXFC", "leagueId" : "3", "regionId" : "", "conferenceId" : "4", "divisionId" : "", "statusId" : "2" },
{ "name" : "Pittsburgh Riverhounds", "abbreviation" : "PGH", "flairClass" : "USL-RIVR", "leagueId" : "3", "regionId" : "", "conferenceId" : "3", "divisionId" : "", "statusId" : "1" },
{ "name" : "Portland Timbers 2", "abbreviation" : "POR2", "flairClass" : "USL-POR2", "leagueId" : "3", "regionId" : "", "conferenceId" : "4", "divisionId" : "", "statusId" : "1" },
{ "name" : "Puerto Rico United",  "abbreviation" : "PRU", "flairClass" : "USL-PRUTD", "leagueId" : "3", "regionId" : "", "conferenceId" : "3", "divisionId" : "", "statusId" : "2" },
{ "name" : "Real Monarchs SLC", "abbreviation" : "SLC2", "flairClass" : "USL-SLC2", "leagueId" : "3", "regionId" : "", "conferenceId" : "4", "divisionId" : "", "statusId" : "1" },
{ "name" : "Reno 1868 FC", "abbreviation" : "REN", "flairClass" : "USL-RENO", "leagueId" : "3", "regionId" : "", "conferenceId" : "4", "divisionId" : "", "statusId" : "2" },
{ "name" : "Richmond Kickers", "abbreviation" : "RIC", "flairClass" : "USL-KIKR", "leagueId" : "3", "regionId" : "", "conferenceId" : "3", "divisionId" : "", "statusId" : "1" },
{ "name" : "Rio Grande Valley FC Toros", "abbreviation" : "RGV", "flairClass" : "USL-RGV", "leagueId" : "3", "regionId" : "", "conferenceId" : "4", "divisionId" : "", "statusId" : "1" },
{ "name" : "River Plate Puerto Rico",  "abbreviation" : "RPPR", "flairClass" : "USL-RPPR", "leagueId" : "3", "regionId" : "", "conferenceId" : "3", "divisionId" : "", "statusId" : "2" },
{ "name" : "Rochester Rhinos", "abbreviation" : "ROC", "flairClass" : "USL-RNOS", "leagueId" : "3", "regionId" : "", "conferenceId" : "3", "divisionId" : "", "statusId" : "1" },
{ "name" : "Sacramento Republic FC", "abbreviation" : "SAC", "flairClass" : "USL-SREP", "leagueId" : "3", "regionId" : "", "conferenceId" : "4", "divisionId" : "", "statusId" : "1" },
{ "name" : "Saint Louis FC", "abbreviation" : "STL", "flairClass" : "USL-STLO", "leagueId" : "3", "regionId" : "", "conferenceId" : "4", "divisionId" : "", "statusId" : "1" },
{ "name" : "San Antonio FC", "abbreviation" : "SAT", "flairClass" : "USL-SAFC", "leagueId" : "3", "regionId" : "", "conferenceId" : "4", "divisionId" : "", "statusId" : "1" },
{ "name" : "Seattle Sounders FC 2", "abbreviation" : "SEA2", "flairClass" : "USL-STL2", "leagueId" : "3", "regionId" : "", "conferenceId" : "4", "divisionId" : "", "statusId" : "1" },
{ "name" : "Sevilla FC Puerto Rico",  "abbreviation" : "SVPR", "flairClass" : "USL-SEVPR", "leagueId" : "3", "regionId" : "", "conferenceId" : "3", "divisionId" : "", "statusId" : "2" },
{ "name" : "Swope Park Rangers KC", "abbreviation" : "SPR", "flairClass" : "USL-SPRKC", "leagueId" : "3", "regionId" : "", "conferenceId" : "4", "divisionId" : "", "statusId" : "1" },
{ "name" : "Toronto FC II", "abbreviation" : "TOR2", "flairClass" : "USL-TFC2", "leagueId" : "3", "regionId" : "", "conferenceId" : "3", "divisionId" : "", "statusId" : "1" },
{ "name" : "Tulsa Roughnecks FC", "abbreviation" : "TUL", "flairClass" : "USL-TULR", "leagueId" : "3", "regionId" : "", "conferenceId" : "4", "divisionId" : "", "statusId" : "1" },
{ "name" : "Vancouver Whitecaps FC 2", "abbreviation" : "VAN2", "flairClass" : "USL-VWC2", "leagueId" : "3", "regionId" : "", "conferenceId" : "4", "divisionId" : "", "statusId" : "1" },
{ "name" : "VSI Tampa Bay",  "abbreviation" : "VTB", "flairClass" : "USL-VSIT", "leagueId" : "3", "regionId" : "", "conferenceId" : "3", "divisionId" : "", "statusId" : "1" },
{ "name" : "Wilmington Hammerheads FC", "abbreviation" : "WIL", "flairClass" : "USL-WHH", "leagueId" : "3", "regionId" : "", "conferenceId" : "3", "divisionId" : "", "statusId" : "1" },
##NPSL##
{ "name" : "AFC Ann Arbor", "abbreviation" : "ANA", "flairClass" : "NPSL-AFCAA", "leagueId" : "4", "regionId" : "3", "conferenceId" : "13", "divisionId" : "", "statusId" : "1" },
{ "name" : "AFC Cleveland", "abbreviation" : "CLE", "flairClass" : "NPSL-ACLEV", "leagueId" : "4", "regionId" : "3", "conferenceId" : "12", "divisionId" : "", "statusId" : "1" },
{ "name" : "Albion SC Pros", "abbreviation" : "ALB", "flairClass" : "NPSL-ALBSC", "leagueId" : "4", "regionId" : "4", "conferenceId" : "17", "divisionId" : "", "statusId" : "1" },
{ "name" : "ASA Charge", "abbreviation" : "ASA", "flairClass" : "NPSL-ASAC", "leagueId" : "4", "regionId" : "1", "conferenceId" : "7", "divisionId" : "", "statusId" : "1" },
{ "name" : "Atlanta Silverbacks", "abbreviation" : "ATL", "flairClass" : "NPSL-ASFC", "leagueId" : "4", "regionId" : "2", "conferenceId" : "8", "divisionId" : "", "statusId" : "1" },
{ "name" : "BCS Clash", "abbreviation" : "BCS", "flairClass" : "NPSL-BCSC", "leagueId" : "4", "regionId" : "2", "conferenceId" : "9", "divisionId" : "", "statusId" : "2"},
{ "name" : "Birmingham Hammers", "abbreviation" : "BIR", "flairClass" : "NPSL-BHAMM", "leagueId" : "4", "regionId" : "2", "conferenceId" : "10", "divisionId" : "", "statusId" : "1" },
{ "name" : "Boston City FC", "abbreviation" : "BOS", "flairClass" : "NPSL-BOSCFC", "leagueId" : "4", "regionId" : "1", "conferenceId" : "5", "divisionId" : "", "statusId" : "1" },
{ "name" : "Brooklyn Italians", "abbreviation" : "BRO", "flairClass" : "NPSL-BROI", "leagueId" : "4", "regionId" : "1", "conferenceId" : "5", "divisionId" : "", "statusId" : "1" },
{ "name" : "Buxmont Torch FC", "abbreviation" : "BUX", "flairClass" : "NPSL-BTFC", "leagueId" : "4", "regionId" : "1", "conferenceId" : "6", "divisionId" : "", "statusId" : "1" },
{ "name" : "Carolina Railhawks U-23", "abbreviation" : "CAR2", "flairClass" : "NPSL-CRU23", "leagueId" : "4", "regionId" : "2", "conferenceId" : "8", "divisionId" : "", "statusId" : "1" },
{ "name" : "CD Aguiluchos USA", "abbreviation" : "AGU", "flairClass" : "NPSL-CDAU", "leagueId" : "4", "regionId" : "4", "conferenceId" : "15", "divisionId" : "", "statusId" : "1" },
{ "name" : "Chattanooga FC", "abbreviation" : "CHA", "flairClass" : "NPSL-CHATFC", "leagueId" : "4", "regionId" : "2", "conferenceId" : "10", "divisionId" : "", "statusId" : "1" },
{ "name" : "Chicago Mustangs", "abbreviation" : "CHI", "flairClass" : "NPSL-CHIM", "leagueId" : "5", "regionId" : "3", "conferenceId" : "14", "divisionId" : "", "statusId" : "2" },
{ "name" : "Chesterfield United FC", "abbreviation" : "CHE", "flairClass" : "NPSL-CUFC", "leagueId" : "4", "regionId" : "1", "conferenceId" : "7", "divisionId" : "", "statusId" : "1" },
{ "name" : "Clarkstown Eagles SC", "abbreviation" : "CLA", "flairClass" : "NPSL-CESC", "leagueId" : "4", "regionId" : "1", "conferenceId" : "6", "divisionId" : "", "statusId" : "1" },
{ "name" : "Corinthians FC of San Antonio", "abbreviation" : "SAT", "flairClass" : "NPSL-CFCSA", "leagueId" : "4", "regionId" : "2", "conferenceId" : "9", "divisionId" : "", "statusId" : "1" },
{ "name" : "Dallas City FC", "abbreviation" : "DAL", "flairClass" : "NPSL-DALCFC", "leagueId" : "4", "regionId" : "2", "conferenceId" : "9", "divisionId" : "", "statusId" : "1" },
{ "name" : "Dayton Dynamo", "abbreviation" : "DAY", "flairClass" : "NPSL-DAYD", "leagueId" : "4", "regionId" : "3", "conferenceId" : "13", "divisionId" : "", "statusId" : "1" },
{ "name" : "Deportivo Coras USA", "abbreviation" : "DCOR", "flairClass" : "NPSL-DCORU", "leagueId" : "4", "regionId" : "4", "conferenceId" : "17", "divisionId" : "", "statusId" : "1" },
{ "name" : "Detroit City FC", "abbreviation" : "DET", "flairClass" : "NPSL-DETCFC", "leagueId" : "4", "regionId" : "3", "conferenceId" : "13", "divisionId" : "", "statusId" : "1" },
{ "name" : "Dutch Lions FC", "abbreviation" : "DUT", "flairClass" : "NPSL-DUT", "leagueId" : "4", "regionId": "6", "conferenceId" : "9", "divisionId" : "", "statusId" : "1" },
{ "name" : "East Bay FC Stompers", "abbreviation" : "EBS", "flairClass" : "NPSL-EBS", "leagueId" : "4", "regionId" : "4", "conferenceId" : "15", "divisionId" : "", "statusId" : "1" },
{ "name" : "Electric City Shock SC", "abbreviation" : "ELE", "flairClass" : "NPSL-ECSCC", "leagueId" : "4", "regionId" : "1", "conferenceId" : "6", "divisionId" : "", "statusId" : "1" },
{ "name" : "Erie Commodores FC", "abbreviation" : "ERI", "flairClass" : "NPSL-ERIC", "leagueId" : "4", "regionId" : "3", "conferenceId" : "12", "divisionId" : "", "statusId" : "1" },
{ "name" : "FC Buffalo", "abbreviation" : "BUF", "flairClass" : "NPSL-FCBUF", "leagueId" : "4", "regionId" : "3", "conferenceId" : "12", "divisionId" : "", "statusId" : "1" },
{ "name" : "FC Carolina Discoveries", "abbreviation" : "FCCAR", "flairClass" : "NPSL-FCCD", "leagueId" : "4", "regionId" : "2", "conferenceId" : "8", "divisionId" : "", "statusId" : "1" },
{ "name" : "FC Frederick", "abbreviation" : "FCFRE", "flairClass" : "NPSL-FCRE", "leagueId" : "4", "regionId" : "1", "conferenceId" : "7", "divisionId" : "", "statusId" : "1" },
{ "name" : "FC Force", "abbreviation" : "FOR", "flairClass" : "NPSL-FCFOR", "leagueId" : "5", "regionId" : "4", "conferenceId" : "17", "divisionId" : "", "statusId" : "1"},
{ "name" : "FC Hasental", "abbreviation" : "HAS", "flairClass" : "NPSL-FCHAS", "leagueId" : "4", "regionId" : "4", "conferenceId" : "17", "divisionId" : "", "statusId" : "1" },
{ "name" : "FC Indiana Lions", "abbreviation" : "FCIND", "flairClass" : "NPSL-FCIND", "leagueId" : "4", "regionId" : "3", "conferenceId" : "12", "divisionId" : "", "statusId" : "1" },
{ "name" : "FC Wichita", "abbreviation" : "WIC", "flairClass" : "NPSL-FCWI", "leagueId" : "4", "regionId" : "2", "conferenceId" : "9", "divisionId" : "", "statusId" : "1" },
{ "name" : "Federal City FC", "abbreviation" : "FED", "flairClass":"NPSL-FEDFC", "leagueId" : "4", "regionId" : "1", "conferenceId" : "7", "divisionId" : "", "statusId": "2" },
{ "name" : "Fort Lauderdale Strikers U-23", "abbreviation" : "FTL2", "flairClass" : "NPSL-FTLS", "leagueId" : "4", "regionId" : "2", "conferenceId" : "11", "divisionId" : "", "statusId" : "1" },
{ "name" : "Fort Pitt FC Regiment", "abbreviation" : "FPR", "flairClass" : "NPSL-FPREG", "leagueId" : "4", "regionId" : "3", "conferenceId" : "12", "divisionId" : "", "statusId" : "1" },
{ "name" : "Fort Worth Vaqueros", "abbreviation" : "FWV", "flairClass" : "NPSL-FWVFC", "leagueId" : "4", "regionId" : "2", "conferenceId" : "9", "divisionId" : "", "statusId" : "1" },
{ "name" : "Fredericksburg FC", "abbreviation" : "FRE", "flairClass" : "NPSL-FREFC", "leagueId" : "4", "regionId" : "1", "conferenceId" : "7", "divisionId" : "", "statusId" : "1" },
{ "name" : "Georgia Revolution FC", "abbreviation" : "GRE", "flairClass" : "NPSL-GREVFC", "leagueId" : "4", "regionId" : "2", "conferenceId" : "8", "divisionId" : "", "statusId" : "1" },
{ "name" : "Grand Rapids FC", "abbreviation" : "GRFC", "flairClass" : "NPSL-GRAPFC", "leagueId" : "4", "regionId" : "3", "conferenceId" : "13", "divisionId" : "", "statusId" : "1" },
{ "name" : "Greater Binghamton FC Thunder", "abbreviation" : "BIN", "flairClass" : "NPSL-GBFCT", "leagueId" : "4", "regionId" : "1", "conferenceId" : "6", "divisionId" : "", "statusId" : "1" },
{ "name" : "Greater Lowell United FC", "abbreviation" : "LOW", "flairClass" : "NPSL-GLUFC", "leagueId" : "4", "regionId" : "1", "conferenceId" : "5", "divisionId" : "", "statusId" : "1" },
{ "name" : "Hershey FC", "abbreviation" : "HER", "flairClass" : "NPSL-HERFC", "leagueId" : "4", "regionId" : "1", "conferenceId" : "6", "divisionId" : "", "statusId" : "1" },
{ "name" : "Houston Regals", "abbreviation" : "HOU", "flairClass" : "NPSL-HRSCA", "leagueId" : "4", "regionId" : "2", "conferenceId" : "9", "divisionId" : "", "statusId" : "1" },
{ "name" : "Indy Eleven NPSL", "abbreviation" : "IND2", "flairClass" : "NPSL-ID11", "leagueId" : "4", "regionId" : "3", "conferenceId" : "12", "divisionId" : "", "statusId" : "1" },
{ "name" : "Jacksonville Armada U-23", "abbreviation" : "JAX2", "flairClass" : "NPSL-JAXA", "leagueId": "4", "regionId" : "2", "conferenceId" : "11", "divisionId" : "", "statusId" : "1" },
{ "name" : "Jacksonville United", "abbreviation" : "JAXU", "flairClass" : "NPSL-JAXU", "leagueId" : "4", "regionId" : "2", "conferenceId" : "11", "divisionId" : "", "statusId" : "2" },
{ "name" : "Jersey Blues FC", "abbreviation" : "JER", "flairClass" : "NPSL-JBFC", "leagueId" : "4", "regionId" : "1", "conferenceId" : "6", "divisionId" : "", "statusId" : "1" },
{ "name" : "Joplin Demize", "abbreviation" : "JOP", "flairClass" : "NPSL-JDFC", "leagueId" : "4", "regionId" : "2", "conferenceId" : "10", "divisionId" : "", "statusId" : "1" },
{ "name" : "Junior Lone Star FC", "abbreviation" : "JUN", "flairClass" : "NPSL-JLSFC", "leagueId" : "4", "regionId" : "1", "conferenceId" : "6", "divisionId" : "", "statusId" : "1" },
{ "name" : "Kalamazoo FC", "abbreviation" : "KAL", "flairClass" : "NPSL-KALFC", "leagueId" : "4", "regionId" : "3", "conferenceId" : "13", "divisionId" : "", "statusId" : "1" },
{ "name" : "Kingston Stockade FC", "abbreviation" : "KIN", "flairClass" : "NPSL-KSFC", "leagueId" : "4", "regionId" : "1", "conferenceId" : "5", "divisionId" : "", "statusId" : "1" },
{ "name" : "Knoxville Force", "abbreviation" : "KXV", "flairClass" : "NPSL-KXVFOR", "leagueId" : "4", "regionId" : "2", "conferenceId" : "10", "divisionId" : "", "statusId" : "1" },
{ "name" : "Kraze United", "abbreviation" : "KRU", "flairClass" : "NPSL-KRAZE", "leagueId" : "4", "regionId" : "2", "conferenceId" : "11", "divisionId" : "", "statusId" : "1" },
{ "name" : "La Crosse Aris FC", "abbreviation" : "LCA", "flairClass" : "NPSL-LCA", "leagueId" : "4", "regionId" : "3", "conferenceId" : "14", "divisionId" : "", "statusId": "2" },
{ "name" : "Lansing United", "abbreviation" : "LAN", "flairClass" : "NPSL-LANU", "leagueId" : "4", "regionId" : "3", "conferenceId" : "13", "divisionId" : "", "statusId" : "1" },
{ "name" : "Legacy 76", "abbreviation" : "LEG", "flairClass" : "NPSL-L76", "leagueId" : "4", "regionId" : "1", "conferenceId" : "7", "divisionId" : "", "statusId" : "1" },
{ "name" : "Little Rock Rangers", "abbreviation" : "LRR", "flairClass" : "NPSL-LRRFC", "leagueId" : "4", "regionId" : "2", "conferenceId" : "9", "divisionId" : "", "statusId" : "1" },
{ "name" : "Liverpool Warriors", "abbreviation" : "LIV", "flairClass" : "NPSL-LPWFC", "leagueId" : "4", "regionId" : "2", "conferenceId" : "9", "divisionId" : "", "statusId" : "1" },
{ "name" : "Memphis City FC", "abbreviation" : "MEM", "flairClass" : "NPSL-MEMCFC", "leagueId" : "4", "regionId" : "2", "conferenceId" : "10", "divisionId" : "", "statusId" : "1" },
{ "name" : "Miami Fusion", "abbreviation" : "MIAF", "flairClass" : "NPSL-MIAFUS", "leagueId" : "4", "regionId" : "2", "conferenceId" : "11", "divisionId" : "", "statusId" : "1" },
{ "name" : "Miami United FC", "abbreviation" : "MIAU", "flairClass" : "NPSL-MIAUTD", "leagueId" : "4", "regionId" : "2", "conferenceId" : "11", "divisionId" : "", "statusId" : "1" },
{ "name" : "Michigan Stars", "abbreviation" : "MICH", "flairClass" : "NPSL-MICHS", "leagueId" : "4", "regionId" : "3", "conferenceId" : "13", "divisionId" : "", "statusId" : "1" },
{ "name" : "Milwaukee Torrent", "abbreviation" : "MILT", "flairClass" : "NPSL-MILT", "leagueId" : "4", "regionId" : "3", "conferenceId" : "14", "divisionId" : "", "statusId" : "2" },
{ "name" : "Minnesota TwinStars", "abbreviation" : "MINT", "flairClass" : "NPSL-MINT", "leagueId" : "4", "regionId": "7", "conferenceId" : "14", "divisionId" : "", "statusId" : "2" },
{ "name" : "Myrtle Beach Mutiny", "abbreviation" : "MYR", "flairClass" : "NPSL-MYRBM", "leagueId" : "4", "regionId" : "2", "conferenceId" : "8", "divisionId" : "", "statusId" : "1" },
{ "name" : "Nashville FC", "abbreviation" : "NAS", "flairClass" : "NPSL-NASHFC", "leagueId" : "4", "regionId" : "2", "conferenceId" : "10", "divisionId" : "", "statusId" : "1" },
{ "name" : "New Jersey Copa FC", "abbreviation" : "NJCFC", "flairClass" : "NPSL-NJCFC", "leagueId" : "4", "regionId" : "1", "conferenceId" : "6", "divisionId" : "", "statusId" : "1" },
{ "name" : "New Orleans Jesters", "abbreviation" : "NOJ", "flairClass" : "NPSL-NOLAJ", "leagueId" : "4", "regionId" : "2", "conferenceId" : "10", "divisionId" : "", "statusId" : "1" },
{ "name" : "New York Athletic Club", "abbreviation" : "NYAC", "flairClass" : "NPSL-NYAC", "leagueId" : "4", "regionId" : "1", "conferenceId" : "5", "divisionId" : "", "statusId" : "1" },
{ "name" : "New York Cosmos B", "abbreviation" : "NYCB", "flairClass" : "NPSL-COSB", "leagueId" : "4", "regionId" : "1", "conferenceId" : "5", "divisionId" : "", "statusId" : "1" },
{ "name" : "North County Battalion", "abbreviation" : "NCB", "flairClass" : "NPSL-NCBAT", "leagueId" : "4", "regionId" : "4", "conferenceId" : "17", "divisionId" : "", "statusId" : "1" },
{ "name" : "OSA FC", "abbreviation" : "OSA", "flairClass" : "NPSL-OSAFC", "leagueId" : "4", "regionId" : "4", "conferenceId" : "16", "divisionId" : "", "statusId" : "1" },
{ "name" : "Real San Jose", "abbreviation" : "RSJ", "flairClass" : "NPSL-REALSJ", "leagueId" : "4", "regionId" : "4", "conferenceId" : "15", "divisionId" : "", "statusId" : "1" },
{ "name" : "Rhode Island Reds", "abbreviation" : "RIR", "flairClass" : "NPSL-RIRED", "leagueId" : "4", "regionId" : "1", "conferenceId" : "5", "divisionId" : "", "statusId" : "1" },
{ "name" : "Rochester River DogZ FC", "abbreviation" : "RRD", "flairClass" : "NPSL-RDOGZ", "leagueId" : "4", "regionId" : "3", "conferenceId" : "12", "divisionId" : "", "statusId" : "1" },
{ "name" : "Sacramento Gold", "abbreviation" : "SACG", "flairClass" : "NPSL-SACG", "leagueId" : "4", "regionId" : "4", "conferenceId" : "15", "divisionId" : "", "statusId" : "1" },
{ "name" : "San Francisco Stompers", "abbreviation" : "SFS", "flairClass" : "NPSL-SFRAS", "leagueId" : "4", "regionId" : "4", "conferenceId" : "15", "divisionId" : "", "statusId" : "2" },
{ "name" : "San Diego Flash", "abbreviation" : "SDF", "flairClass" : "NPSL-SDFL", "leagueId" : "4", "regionId" : "4", "conferenceId" : "17", "divisionId" : "", "statusId" : "2" },
{ "name" : "Seacoast United Mariners", "abbreviation" : "SUM", "flairClass" : "NPSL-SUMAR", "leagueId" : "4", "regionId" : "1", "conferenceId" : "5", "divisionId" : "", "statusId" : "1" },
{ "name" : "Seacoast United Phantoms", "abbreviation" : "SUP", "flairClass" : "NPSL-SUPHA", "leagueId" : "4", "regionId" : "1", "conferenceId" : "5", "divisionId" : "", "statusId" : "1" },
{ "name" : "Shreveport Rafters FC", "abbreviation" : "SRFC", "flairClass" : "NPSL-SRFC", "leagueId" : "4", "regionId" : "2", "conferenceId" : "9", "divisionId" : "", "statusId" : "1" },
{ "name" : "Southern California Sports Club", "abbreviation" : "SCSC", "flairClass" : "NPSL-SCALSC", "leagueId" : "4", "regionId" : "4", "conferenceId" : "17", "divisionId" : "", "statusId" : "1" },
{ "name" : "Spartans FC", "abbreviation" : "SPA", "flairClass" : "NPSL-SPAFC", "leagueId" : "4", "regionId" : "4", "conferenceId" : "16", "divisionId" : "", "statusId" : "1" },
{ "name" : "Corinthians USA", "abbreviation" : "SCC", "flairClass" : "NPSL-SCCUSA", "leagueId" : "4", "regionId" : "4", "conferenceId" : "17", "divisionId" : "", "statusId" : "1" },
{ "name" : "Storm FC", "abbreviation" : "STO", "flairClass" : "NPSL-STOFC", "leagueId" : "4", "regionId" : "2", "conferenceId" : "11", "divisionId" : "", "statusId" : "1" },
{ "name" : "Sonoma County Sol", "abbreviation" : "SCS", "flairClass" : "NPSL-SCSOL", "leagueId" : "4", "regionId" : "4", "conferenceId" : "15", "divisionId" : "", "statusId" : "1" },
{ "name" : "Tampa Bay Rowdies 2", "abbreviation" : "TBR2", "flairClass" : "NPSL-TBR2", "leagueId" : "4", "regionId" : "2", "conferenceId" : "11", "divisionId" : "", "statusId" : "1" },
{ "name" : "Temecula FC", "abbreviation" : "TEM", "flairClass" : "NPSL-TEMFC", "leagueId" : "4", "regionId" : "4", "conferenceId" : "17", "divisionId" : "", "statusId" : "1" },
{ "name" : "Tobacco Road", "abbreviation" : "TOB", "flairClass" : "NPSL-TROAD", "leagueId" : "4", "regionId" : "2", "conferenceId" : "8", "divisionId" : "", "statusId" : "1" },
{ "name" : "Tulsa Athletics", "abbreviation" : "TUL", "flairClass" : "NPSL-TULA", "leagueId" : "4", "regionId" : "2", "conferenceId" : "9", "divisionId" : "", "statusId" : "1" },
{ "name" : "Virginia Beach City FC", "abbreviation" : "VBC", "flairClass" : "NPSL-VBCFC", "leagueId" : "4", "regionId" : "1", "conferenceId" : "7", "divisionId" : "", "statusId" : "1" },
{ "name" : "Weston FC", "abbreviation" : "WES", "flairClass" : "NPSL-WESFC", "leagueId" : "4", "regionId" : "2", "conferenceId" : "11", "divisionId" : "", "statusId" : "1" },
##NWSL##
{ "name" : "Boston Breakers", "abbreviation" : "BOS", "flairClass" : "NWSL-BOS", "leagueId" : "5", "regionId" : "", "conferenceId" : "", "divisionId" : "", "statusId" : "1" },
{ "name" : "Chicago Red Stars", "abbreviation" : "CRS", "flairClass" : "NWSL-CRS", "leagueId" : "5", "regionId" : "", "conferenceId" : "", "divisionId" : "", "statusId" : "1" },
{ "name" : "FC Kansas City", "abbreviation" : "FCKC", "flairClass" : "NWSL-FCKC", "leagueId" : "5", "regionId" : "", "conferenceId" : "", "divisionId" : "", "statusId" : "1" },
{ "name" : "Houston Dash", "abbreviation" : "HOU", "flairClass" : "NWSL-HOU", "leagueId" : "5", "regionId" : "", "conferenceId" : "", "divisionId" : "", "statusId" : "1" },
{ "name" : "Orlando Pride", "abbreviation" : "ORL", "flairClass" : "NWSL-ORL", "leagueId" : "5", "regionId" : "", "conferenceId" : "", "divisionId" : "", "statusId" : "1" },
{ "name" : "Portland Thorns", "abbreviation" : "PTFC", "flairClass" : "NWSL-PTFC", "leagueId" : "5", "regionId" : "", "conferenceId" : "", "divisionId" : "", "statusId" : "1" },
{ "name" : "Seattle Reign FC", "abbreviation" : "SRFC", "flairClass" : "NWSL-SRFC", "leagueId" : "5", "regionId" : "", "conferenceId" : "", "divisionId" : "", "statusId" : "1" },
{ "name" : "Sky Blue FC", "abbreviation" : "SBFC", "flairClass" : "NWSL-SBFC", "leagueId" : "5", "regionId" : "", "conferenceId" : "", "divisionId" : "", "statusId" : "1" },
{ "name" : "Wasington Spirit", "abbreviation" : "WAS", "flairClass" : "NWSL-WAS", "leagueId" : "5", "regionId" : "", "conferenceId" : "", "divisionId" : "", "statusId" : "1" },
{ "name" : "Western New York Flash", "abbreviation" : "WNYF", "flairClass" : "NWSL-WNYF", "leagueId" : "5", "regionId" : "", "conferenceId" : "", "divisionId" : "", "statusId" : "1" }
]



